# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First player to move'), ('S', 'Second player to move'), ('W', 'First player wins'), ('L', 'Second player wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
